name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set image tag
      run: echo "IMAGE_TAG=mass-gym:$(date +%s)" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Run the Docker image
      run: docker run ${{ env.IMAGE_TAG }}
      